<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SDL.Tests.Browser</RootNamespace>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <WasmMainJSPath>main.js</WasmMainJSPath>
    <InvariantGlobalization>true</InvariantGlobalization>
    <WasmBuildNative>true</WasmBuildNative>
    <WasmNativeStrip>true</WasmNativeStrip>
    <WasmAllowUndefinedSymbols>true</WasmAllowUndefinedSymbols>
  </PropertyGroup>

  <PropertyGroup Label="NuGet">
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SDL3-CS\SDL3-CS.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <WasmExtraFilesToDeploy Include="index.html"/>
    <WasmExtraFilesToDeploy Include="main.js"/>
    <NativeFileReference Include="..\native\browser-wasm\libSDL3.a"/>
  </ItemGroup>

  <Choose>
    <When Condition=" '$(Configuration)' == 'Debug' ">
      <PropertyGroup>
        <WasmEmitSymbolMap>true</WasmEmitSymbolMap>
        <EmccFlags>-sUSE_WEBGL2=1 -sFULL_ES3=1 -sMIN_WEBGL_VERSION=2 -sMAX_WEBGL_VERSION=2 -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=64MB -sMAXIMUM_MEMORY=512MB -O1 -g</EmccFlags>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <EmccFlags>-sUSE_WEBGL2=1 -sFULL_ES3=1 -sMIN_WEBGL_VERSION=2 -sMAX_WEBGL_VERSION=2 -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=64MB -sMAXIMUM_MEMORY=512MB -O3</EmccFlags>
      </PropertyGroup>
    </Otherwise>
  </Choose>

</Project>
